name: CI

on:
  push:
    branches:
      - main
      - production
      - new_staging
      - new_staging2
      - 'feature/**'
      - 'product/**'
  pull_request:
    branches:
      - main
      - production
      - new_staging
      - new_staging2
      - 'product/**'

jobs:
  validate:
    uses: ./.github/workflows/validate-reusable.yml
    with:
      git_branch: ${{ github.ref_name }}
